language: r
sudo: false
cache: packages
dist: trusty

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        
before_install:
  - mkdir -p ~/.R/
  - echo "CXX14 = g++-7 -fPIC" >> ~/.R/Makevars
  - echo "CXXFLAGS = -O3" >> ~/.R/Makevars