language: r
sudo: false
cache: packages
dist: trusty

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        
before_install:
  - mkdir -p ~/.R/
  - echo "CXX14 = g++-7 -fPIC" >> ~/.R/Makevars
  - echo "CXXFLAGS = -mtune=native -march=native -Wno-unused-variable -Wno-unused-function  -Wno-macro-redefined -O3" >> ~/.R/Makevars
  
after_install:
  - cat /home/travis/build/saudiwin/idealstan/idealstan.Rcheck/00install.out