language: r
sudo: false
cache: packages
dist: trusty

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7 && CXX14=g++-7 && CXX14FLAGS = -O3"
        
before_install:
    - eval "${MATRIX_EVAL}"